---
abstract: 'Interface for Chef Clients REST API'
author:
  - 'Bhavin Patel <bpatel10@nyit.edu>'
build_requires:
  English: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132510'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chef-REST-Client
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::OpenSSL::RSA: 0
  File::Basename: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  LWP::UserAgent: 0
  Module::Load: 0
  Mojo::JSON: 0
version: 1.1
